name: Rerun Jupyter Notebook

on:
  push:
    paths:
      - "**/*.ipynb"
      - "**/*.py"
      - ".github/workflows/jupyter_rerun.yml"

jobs:
  rerun-notebook:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install jupyter nbconvert wandb opencv-python matplotlib numpy scikit-learn python-dotenv scipy opencv-python-headless ipykernel

      - name: Download haarcascade_frontalface_default.xml
        run: |
          mkdir -p images
          wget -O images/haarcascade_frontalface_default.xml https://github.com/opencv/opencv/raw/master/data/haarcascades/haarcascade_frontalface_default.xml

      - name: Configure wandb
        env:
          WANDB_API_KEY: ${{ secrets.WANDB_API_KEY }}
        run: |
          wandb login $WANDB_API_KEY

      - name: Execute Jupyter Notebook
        run: |
          jupyter nbconvert --to notebook --execute "lab_5.ipynb" --output "output_notebook.ipynb" --ExecutePreprocessor.kernel_name=python3 --debug

      - name: Log metrics and images to wandb
        env:
          WANDB_API_KEY: ${{ secrets.WANDB_API_KEY }}
        run: |
          python -c "
          import wandb
          wandb.login(key='$WANDB_API_KEY')
          wandb.init(project='distance_classification_project')
          wandb.save('output_notebook.ipynb')
          "
